// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'ItemPropertiesPanel': string;
  'frmPropsAnchor': string;
  'frmPropsLoading': string;
  'frmPropsLoadingHidden': string;
  'frmViewPanel': string;
  'panel': string;
}
const cssExports: CssExports;
export default cssExports;
