// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'commandBar': string;
  'commandbarLabelItem': string;
  'fadein': string;
  'frmDocumentReader': string;
  'hidden': string;
  'loading': string;
  'mgCustomIcon': string;
  'pnlLoading': string;
  'readerPanel': string;
  'results': string;
}
const cssExports: CssExports;
export default cssExports;
