// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'numberEnd': string;
  'numberEndHidden': string;
  'numberOperator': string;
  'numberRange': string;
  'pickerRow': string;
}
const cssExports: CssExports;
export default cssExports;
