// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'PeoplePicker': string;
}
const cssExports: CssExports;
export default cssExports;
