define([], function() {
  return {
    "PropertyPaneDescription": "Advanced Searh Settings",
    "BasicGroupName": "Group Name",
    "IncludeKeywordSearchLabel": "Include Keyword Search Box",
    "SearchConfigFieldLabel": "Search Interface Config",
    "SearchConfigFieldDesc": "JSON string describing the search interface",
    "IsDebugFieldLabel": "Debug Mode",
    "AddCriteriaFieldLabel": "Additional Search Criteria",
    "AddCriteriaFieldDesc": "Text here will be included with each search query. Example: IsDocument=1",
    "StartMinimizedLabel": "Start Minimized",
    "GreaterThanName": "Greater Than",
    "GreatherThanPlaceholder1": "Lower Bounds",
    "LessThanName": "Less Than",
    "LessThanPlaceholder1": "Upper Bounds",
    "BetweenName": "Between",
    "BetweenSymbol": "Between",
    "BetweenNumericPlaceholder1": "Lower Bounds",
    "BetweenNumericPlaceholder2": "Upper Bounds",
    "BetweenDatePlaceholder1": "Beginning",
    "BetweenDatePlaceholder2": "Ending",
    "ContainsName": "Contains",
    "GreaterThanEqualsName": "Greater Than Equals or Equals",
    "GreaterThanEqualsPlaceholder1": "Lower Bounds",
    "LessThanEqualsName": "Less Than or Equals",
    "LessThanEqualsPlaceholder1": "Upper Bounds",
    "EqualsName": "Equals",
    "EqualsSymbol": "Equals",
    "EqualsPlaceholder1": "Number",
    "AfterName": "After",
    "AfterPlaceholder1": "Beginning",
    "BeforeName": "Before",
    "BeforePlaceholder1": "Ending",
    "OnName": "On",
    "OnPlaceholder1": "Date"
  }
});